# Park data
This notebook is to preprocess the park data in vic

### Read files

In [2]:
import pandas as pd

csv_file_path = '../data/raw/location_postcode(1).csv'
postcode = pd.read_csv(csv_file_path).dropna().drop_duplicates(subset=['SA2_NAME_2016'])

In [6]:


csv_file_path = '../data/raw/parks-and-reserves1.csv'
park = pd.read_csv(csv_file_path)  

# print(df.head())

### Get the suburb file

In [3]:
postcode['SA2_NAME_2016'] = [x.replace(" ", "").upper().split('-')[0].strip() for x in postcode['SA2_NAME_2016'].tolist() if x is not None]
postcode

,postcode,locality,SA2_MAINCODE_2016,SA2_NAME_2016,Lat_precise,Long_precise
0,3000,melbourne,206041122.0,MELBOURNE,-37.815207,144.963937
2,3002,east melbourne,206041119.0,EASTMELBOURNE,-37.816144,144.980459
3,3003,west melbourne,206041127.0,WESTMELBOURNE,-37.811450,144.925397
4,3004,melbourne,206041126.0,SOUTHBANK,-37.830158,144.980459
5,3004,st kilda road central,206041125.0,SOUTHYARRA,-37.836800,144.976000
...,...,...,...,...,...,...
3444,3977,cranbourne,212031300.0,CRANBOURNE,-38.105000,145.279000
3445,3977,cranbourne east,212031301.0,CRANBOURNEEAST,-38.116335,145.307612
3446,3977,cranbourne north,212031302.0,CRANBOURNENORTH,-38.070000,145.291000
3448,3977,cranbourne west,212031304.0,CRANBOURNEWEST,-38.102173,145.253545
3452,3977,sandhurst,214011376.0,SKYE,-38.081000,145.207000

In [4]:
postcode.dtypes

postcode               int64
locality              object
SA2_MAINCODE_2016    float64
SA2_NAME_2016         object
Lat_precise          float64
Long_precise         float64
dtype: object

Park preprocessing

### Join with the park dataset

In [7]:
park

,geo_point_2d,name,latitude,longitude,address,area,suburb_name,postcode,ward_name,easting,northing,projection,googlemaps_drive_to
0,"-38.0686242710788, 145.29010411975798",Glasscocks Road from Norwegian Way to Chatswoo...,-38.068252,145.288488,763P Glasscocks Road NARRE WARREN SOUTH,4513.0,NARRE WARREN SOUTH,NaN,SPRINGFIELD,350001,5785183,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.068251...
1,"-37.99379450846953, 145.2285867916676",Claret Street Undeveloped,-37.993916,145.230284,Claret Street DOVETON,5673.0,DANDENONG,NaN,NaN,344434,5793394,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-37.993915...
2,"-38.057147891496776, 145.36740350642918",Brookvale Close Reserve,-38.057068,145.368004,50-52I Brookvale Close BEACONSFIELD,3819.0,BEACONSFIELD,NaN,EDRINGTON,356768,5786584,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.057068...
3,"-37.99224476549151, 145.31344676049073",Narre Warren North Road at Fox Road,-37.993186,145.313325,Narre Warren North Road NARRE WARREN NORTH,2900.0,NARRE WARREN NORTH,NaN,FOUR OAKS,351905,5793702,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-37.993185...
4,"-38.01518314179375, 145.31937110545107",Ryelands Drive and Hillcrest Avenue Tree Reserve,-38.017290,145.318246,Ryelands Drive BERWICK,4679.0,BERWICK,NaN,EDRINGTON,352518,5791105,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.017290...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3259,"-38.12438169701967, 145.3730096551682",Pattersons Median west of Orana,-38.124433,145.373448,Pattersons Road CLYDE NORTH,255.0,CLYDE,3978.0,BALLA BALLA,357389,5779136,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.124433...
3260,"-38.07614423025113, 145.36416724802945",Charleston Chase - Masquerade Road tree reserve,-38.076620,145.363471,Bells Road BERWICK,3225.0,BERWICK,3806.0,EDRINGTON,356560,5784502,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.076619...
3261,"-38.129022909683485, 145.3297061972515",Swanston Street Reserve,-38.128512,145.328783,110S Twyford Road CLYDE,50249.0,CLYDE,3978.0,BALLA BALLA,353607,5778537,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.128512...
3262,"-38.11465224934369, 145.25929592328202",Copley Street Reserve,-38.115009,145.259665,Copley Street CRANBOURNE WEST,5972.0,CRANBOURNE,3977.0,BALLA BALLA,347405,5780036,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.115009...
3263,"-38.11243022321195, 145.2590677328183",Stringer Avenue Reserve,-38.112300,145.258909,Stringer Avenue CRANBOURNE,760.0,CRANBOURNE,3977.0,BALLA BALLA,347379,5780278,MGA2020 Zone 55,https://www.google.com.au/maps/dir//-38.112299...

In [8]:
# drop columns
columns_to_drop = ['geo_point_2d', 'postcode', 'ward_name','easting','northing','projection','googlemaps_drive_to','area']
park_drop = park.drop(columns=columns_to_drop) # 创建一个新的 DataFrame，不修改原始 DataFrame
#park_drop = park_drop.drop(park_drop.columns[0], axis=1)
park_drop

,name,latitude,longitude,address,suburb_name
0,Glasscocks Road from Norwegian Way to Chatswoo...,-38.068252,145.288488,763P Glasscocks Road NARRE WARREN SOUTH,NARRE WARREN SOUTH
1,Claret Street Undeveloped,-37.993916,145.230284,Claret Street DOVETON,DANDENONG
2,Brookvale Close Reserve,-38.057068,145.368004,50-52I Brookvale Close BEACONSFIELD,BEACONSFIELD
3,Narre Warren North Road at Fox Road,-37.993186,145.313325,Narre Warren North Road NARRE WARREN NORTH,NARRE WARREN NORTH
4,Ryelands Drive and Hillcrest Avenue Tree Reserve,-38.017290,145.318246,Ryelands Drive BERWICK,BERWICK
...,...,...,...,...,...
3259,Pattersons Median west of Orana,-38.124433,145.373448,Pattersons Road CLYDE NORTH,CLYDE
3260,Charleston Chase - Masquerade Road tree reserve,-38.076620,145.363471,Bells Road BERWICK,BERWICK
3261,Swanston Street Reserve,-38.128512,145.328783,110S Twyford Road CLYDE,CLYDE
3262,Copley Street Reserve,-38.115009,145.259665,Copley Street CRANBOURNE WEST,CRANBOURNE
3263,Stringer Avenue Reserve,-38.112300,145.258909,Stringer Avenue CRANBOURNE,CRANBOURNE

In [9]:
# drop null
park_drop = park_drop.dropna(subset=['name'])
filtered_park = park_drop[park_drop['name'].str.contains('garden|reserve', case=False, regex=True)]

In [10]:
filtered_park['suburb_name'] = [x.replace(" ", "").strip() for x in filtered_park['suburb_name'].tolist()]

/var/folders/7h/db9rqv7j4mbfc37p_n0qm54m0000gn/T/ipykernel_59982/946483077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_park['suburb_name'] = [x.replace(" ", "").strip() for x in filtered_park['suburb_name'].tolist()]

In [11]:
filtered_park.count()

name           1000
latitude       1000
longitude      1000
address         992
suburb_name    1000
dtype: int64

In [12]:
filtered_park.columns

Index(['name', 'latitude', 'longitude', 'address', 'suburb_name'], dtype='object')

In [13]:
filtered_park.dtypes

name            object
latitude       float64
longitude      float64
address         object
suburb_name     object
dtype: object

In [14]:
postcode.columns = ['postcode', 'locality', 'SA2_MAINCODE_2016',
                    'suburb_name', 'latitude', 'longitude']
postcode = postcode.loc[:, ['postcode', 'suburb_name']].drop_duplicates().drop_duplicates(subset=['suburb_name'])
postcode

      postcode      suburb_name
0         3000        MELBOURNE
2         3002    EASTMELBOURNE
3         3003    WESTMELBOURNE
4         3004        SOUTHBANK
5         3004       SOUTHYARRA
...        ...              ...
3444      3977       CRANBOURNE
3445      3977   CRANBOURNEEAST
3446      3977  CRANBOURNENORTH
3448      3977   CRANBOURNEWEST
3452      3977             SKYE

[421 rows x 2 columns]

In [15]:
merge_df = pd.merge(filtered_park, postcode, on=['suburb_name'], how='left')

In [16]:
merge_df

,name,latitude,longitude,address,suburb_name,postcode
0,Brookvale Close Reserve,-38.057068,145.368004,50-52I Brookvale Close BEACONSFIELD,BEACONSFIELD,3807.0
1,Ryelands Drive and Hillcrest Avenue Tree Reserve,-38.017290,145.318246,Ryelands Drive BERWICK,BERWICK,3806.0
2,Hinrichsen Drive Reserve,-38.014240,145.283707,127-129 Hinrichsen Drive HALLAM,HALLAM,3803.0
3,Lawson Way Reserve,-37.976977,145.266181,78-92I Heatherton Road ENDEAVOUR HILLS,ENDEAVOURHILLS,3156.0
4,Western Way Tree Reserve,-38.022186,145.296446,401I Princes Highway NARRE WARREN,NARREWARREN,3805.0
...,...,...,...,...,...,...
995,Artois Road Reserve,-38.048459,145.323247,"Artois Road, BERWICK",BERWICK,3806.0
996,Charleston Chase - Masquerade Road tree reserve,-38.076620,145.363471,Bells Road BERWICK,BERWICK,3806.0
997,Swanston Street Reserve,-38.128512,145.328783,110S Twyford Road CLYDE,CLYDE,NaN
998,Copley Street Reserve,-38.115009,145.259665,Copley Street CRANBOURNE WEST,CRANBOURNE,3977.0
999,Stringer Avenue Reserve,-38.112300,145.258909,Stringer Avenue CRANBOURNE,CRANBOURNE,3977.0

In [17]:
merge_df[merge_df['postcode'].isnull()]

,name,latitude,longitude,address,suburb_name,postcode
6,Belvista Way Reserve,-38.144123,145.254334,4I Belvista Way BOTANIC RIDGE,BOTANICRIDGE,NaN
7,Melington Drive Reserve,-38.070810,145.241351,320-400I Dandenong-Hastings Road LYNDHURST,LYNDHURST,NaN
8,Adriana Circuit Wetland Reserve,-38.147536,145.252734,23S Adriana Circuit BOTANIC RIDGE,BOTANICRIDGE,NaN
13,Yannathan Street Reserve,-38.209955,145.381267,30 Yannathan Street TOORADIN,TOORADIN,NaN
23,Dundass Grove Tree Reserve,-38.136974,145.260289,Dundass Grove BOTANIC RIDGE,BOTANICRIDGE,NaN
...,...,...,...,...,...,...
986,Gecko Drive Reserve,-38.105334,145.341864,NaN,CLYDENORTH,NaN
989,Lyndhurst Boulevard Tree Reserve,-38.067775,145.249195,Lyndhurst Boulevard LYNDHURST,LYNDHURST,NaN
991,Booring Recreational Reserve,-38.150665,145.285438,"81 Browns Road, BOTANIC RIDGE",BOTANICRIDGE,NaN
992,Murrumbidgee Drive Reserve,-38.133617,145.367327,"Murrumbidgee Drive, CLYDE",CLYDE,NaN
997,Swanston Street Reserve,-38.128512,145.328783,110S Twyford Road CLYDE,CLYDE,NaN

### Save the files

In [19]:
merge_df.to_csv('../data/curated/finally_park.csv', index=False)